sudu: required
services:
  - docker

before_install:
  - docker build -t eakkawatlo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eakkawatlo/docker-react npm run test -- --coverage
